# Build Stage
ARG NODE_ENV="production"
ARG NODE_IMAGE="16.18.1-alpine3.16"

FROM node:${NODE_IMAGE} as builder

WORKDIR /app
COPY ./app/nuxt-app/ /app
RUN npm install
EXPOSE 3000
ENV HOST 0.0.0.0
ENV NUXT_PORT=3000

#RUN npx browserslist@latest --update-db

#RUN npm install caniuse-lite
RUN npm run build

# For Dev run this command CMD [ "npm", "run", "dev" ]
# For Prod run this command
ENTRYPOINT [ "npm", "run", "start" ]
